apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name:  {{ .Release.Name }}-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - {{ .Values.app.url }}
      secretName: {{ .Release.Name }}-tls
  ingressClassName: nginx
  rules:
    - host: {{ .Values.app.url }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: 80