APP_URL: ENC[AES256_GCM,data:g7cJYND6TSAqFCESCVxy,iv:BWUa56LkirfEUXKI9zN0C0Bs7vYfpQSuev6WbvfmcJg=,tag:WLTsXhUK8HGVyX1yuqshuA==,type:str]
CODE_REPO: ENC[AES256_GCM,data:QG0rdlYIxB4NKRPTPzY=,iv:OJkt4cULghsCtQnnDhLEx7wFx8c1VDEManiG5pg3Vvw=,tag:a3sOE/7Jr/Z0PduorixziA==,type:str]
PROJECT_DIR: ENC[AES256_GCM,data:NpK9YHDHXYZtpDLQskVX+tgMBgVC7fOsJOu2bg==,iv:sLWdebsIHrX+jsx+9v9KN6NX7RKtU4dAc+XVyaOklbU=,tag:VjBkNaa5zqERqSIvDpTHmQ==,type:str]
WEB_PORT: ENC[AES256_GCM,data:99q83Q==,iv:6hOVUi5/AAItEtKbHITuO5wER2i5hYRM5Tw8t0Wi4gc=,tag:fWgyeyAat1uLBxXU1A3rtQ==,type:str]
APP_PORT: ENC[AES256_GCM,data:55SADfhXEXHcN0xArO4=,iv:4sTQe7qzq6sYVVEQgWHfYRvT9BT3BxaNCQ0B/EB3huo=,tag:/Lx8cBRtbVSwLwJ4NKT9LA==,type:str]
WEB_SERVER_USER: ENC[AES256_GCM,data:WGNweXxp/LY=,iv:fZnMr/S0sXNagTJW/iWI+2PIDZgAf5pwcn/W6lt9uc0=,tag:PMQg0ZOwKAOLVJ1Mh/CBGQ==,type:str]
DOCKER_USERNAME: null
DOCKER_PASSWORD: null
DOCKER_EMAIL: ENC[AES256_GCM,data:GRtal0eOHOhRh97jSlFQMKLs7g==,iv:S9DCCLT67FVlAis9GFtvAE+XkdHWbVoAxjNvPOSwYnA=,tag:XxVXWd0SEcLji3I8OAj/gg==,type:str]
DOCKER_REPO: ENC[AES256_GCM,data:YbZRCyZ7UN16hJWaeqL5nXUHpQ==,iv:I/BIAPoUaaFYq0qJm9jbU7oCqaOF2j5SXpNQxvV+5x0=,tag:7anECegzOBP/nAvSWKNSVw==,type:str]
DOCKER_PORTS:
    - ENC[AES256_GCM,data:ubkVIsCtg0vLy+YAt875imNOyuMuFwo3bmlO10+0G4jgyioZWEM2,iv:GIVOArNznXYxvgoCc1nN+S4rDZzuI+gUuRIqodNlmAg=,tag:UHJUhmlvDaGqY7bXZ8n4Uw==,type:str]
DOCKER_ENV:
    NEXT_PUBLIC_EXCHANGE_RATE_API_URL: ENC[AES256_GCM,data:rQtjqCLAlV0Urv+6kR9IcacxnAUlS9jCwKMktCpuKbClR3g=,iv:pUx1Ji78d6gvqlvUo1T7mFuqxotja3SQtXOq3FxQfq4=,tag:cnBpNNPRKDntj1HxqiQoMw==,type:str]
    NEXT_PUBLIC_TRANSLATION_API_URL: ENC[AES256_GCM,data:Epp/TTcnr6aCsaGa47Wyd6E8g1HLD7VLIzv8rWIWD0vfJRo=,iv:Mtrsz8NxxkxPKfeyUPSPjwhGsDVRbF10n8sS7hhKmbY=,tag:cJSvkbQu7GXIZTbl42/gzA==,type:str]
    NEXT_PUBLIC_IMAGE_PROCESSING_API_URL: ENC[AES256_GCM,data:pdhWpJhD+S6WLqalG4fISFrmfxXH1/jB9hp2M+4=,iv:OdvHhCArvBwjjIYo06eRGdoYyNjdzQkq9wH+kA5BBS4=,tag:KzKDcCBgF7u8xy+cRHT+Jw==,type:str]
    NEXT_PUBLIC_BARCODE_API_URL: ENC[AES256_GCM,data:1QXlziF/RSNAXMIn6mnV3v0jJn6LdWPIElt2LZnPbQ==,iv:mun58rwndg8gVHYvzTfr//MS+foBQnD8tsH/MzM1tIA=,tag:om4DI0MPRovaeWr/lzTwYA==,type:str]
    NEXT_PUBLIC_PDF_API_URL: ENC[AES256_GCM,data:/KZvcxKnoTYYyBXaEQ+riVy2xAfT7wj3LRQD,iv:TvhxNFykN8sTJ+jP2mLayTNsg/4p7QxyhL5Tx/d+weo=,tag:BT+5JA9OgIKvXxwwFDkY2g==,type:str]
force_config: ENC[AES256_GCM,data:LIPUvQ==,iv:VHoH/KqVIZF26by39/gZeilV4Zxm0LrCfM/Q4sKhyrs=,tag:b02vsxXG5Kyi5CtqIxC2rg==,type:bool]
LETSENCRYPT_EMAIL: ENC[AES256_GCM,data:EpM0+D9WwixKbw0H0i9ZMUgWuLi0cv3c,iv:EGIa1lgI/drDSTEhNiIsnLKLO6WnkIhqvfb2+X8u2Ww=,tag:O7WYXFMILfE5a7SBPzawLA==,type:str]
LETSENCRYPT_DIR: ENC[AES256_GCM,data:VRIYXtMFfXKvWb3kSkVbG4qtuJIL,iv:FhQp0m3kN6YRvbty9tpy617ErbGlMcn6Stm7US5VRbQ=,tag:x9TcEScqk3lNkY7P7a/DfQ==,type:str]
DOCKER_LOG_DRIVER: ENC[AES256_GCM,data:4BG6JryTPg==,iv:hzY54N+LJD/33ti5k60VhdYCNqK8EGdoNpRJux4Uesc=,tag:cd5MJ1l1B+mtWfv3XOMo2w==,type:str]
DOCKER_LOG_OPTIONS:
    awslogs-region: ENC[AES256_GCM,data:qrI7oyKk58c7Nfbou5I=,iv:sD6b5lQmQsnkHgCTjK7bGvaWhQ6zkmb6n2TEPp3vBzs=,tag:NI5jgJEJOFVWuJthroAx/A==,type:str]
    awslogs-group: ENC[AES256_GCM,data:RftJyWrpftH1Z+P0AsXlTGzYEMFbjNA16C0K,iv:/CTwmosVRg8OeZ89vHLyh4If5Xn2h0a13PCfisZyQv4=,tag:HtV6sQV8JtpgfWQPECsosA==,type:str]
    awslogs-create-group: ENC[AES256_GCM,data:Dz0Z5w==,iv:HEPOOOZDo70vUQ6RdzLBdXgsW5Zd6ryr75WjiyLembw=,tag:hVloEs2JteYNINPSL8ZurQ==,type:bool]
    awslogs-stream: ENC[AES256_GCM,data:eIaytQGh8aNwC26BgnuiZxs1dMbfApc=,iv:GeKqZWNeEaAN6oxBCqHoT8R1fjpL/P5GataWRSokFuY=,tag:7PL5uyOLuZTJyihf7HtXxg==,type:str]
certbot_create_if_missing: ENC[AES256_GCM,data:d++v6Q==,iv:nb5TGish4ETtdYfA6KBMtqDjU/hEWVLWVRdkHO2DIEY=,tag:5sGui8+EhYTyYBsn6FDwdA==,type:bool]
certbot_dir: ENC[AES256_GCM,data:m/UW7vFZv9NyN5IoTmZvHiF6deEW,iv:zX/OjgkJGr/j0R9uk0Jfl6Z6/unjzvTIMPvfMXPKJ/A=,tag:SiYVNeMjiSA7huBcvYGXtw==,type:str]
certbot_create_standalone_stop_services:
    - ENC[AES256_GCM,data:xxfzqMU=,iv:c95AqAtqkrQqTc2rxrLP4K7QbPjb1HhEl7F7JbMLkp4=,tag:qRySABOAa6TUWbWm2wrzBw==,type:str]
certbot_certs:
    - email: ENC[AES256_GCM,data:q87tpFYVKwsI4zRzYbZ9diUyVw0jXls=,iv:NgV2F9aRe/dlJ6QSUf9xtvIh7saJqheUwEX0rt/wfc4=,tag:rsRKZKafXSaFMjQboJmevw==,type:str]
      domains: ENC[AES256_GCM,data:q0q2b9BnecCek0avuCm6UeypTPhWbAUTnM8BBBSrNYw=,iv:HIf108f9jNo3HoxrXGKRUd2q+vZ/pnNHmEVYQKq1H1k=,tag:eAYLWxJE5c9INJZ40NzAow==,type:str]
certbot_keep_updated: ENC[AES256_GCM,data:f2RG,iv:cF1BkDqHHhovzYyzWsonWco45KYkLkThDuJx984gzpk=,tag:jkm1w6K8/d9yZ0A7gph56w==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:ap-southeast-1:143188609111:key/8fc6f01a-3289-4fb4-b9e7-cab31c54a4ea
          created_at: "2025-03-07T16:00:52Z"
          enc: AQICAHgxToX4Pp90hvfJQ4E9+h6aXlRo2IWXaPLiRXBaMnIbJwEElaOIyJuIH9JDAIlOgT+EAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMZQQfWkchRTya5gFFAgEQgDtxJUav6o1gyIlhkLwdDnEMwgsy8x08PbdwpuYgFatOo1gi7zKE7t8xey0aFg52Hezcqw995SM5Xmdtwg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-07T16:00:52Z"
    mac: ENC[AES256_GCM,data:U5kv2i4J1RAJakCetDDBcEoEt7NBiLjt9jMixLywIuhtsS5XMktFXsQ1W3fS6UoF2bpfW2Z0FSBdTSftHXOYpgHInM8MjX7eC4zW2ox6FSicutHxqoxmbTYbXHx/v05DQhJF882uexhtZr8fEWgdzh8EvBHlLxN4wpc2mdxS30E=,iv:CyehsZn3J0a33uLrs8sJ1KwfugYsah/a8R7MqTtCTUE=,tag:npfHeiqu9Qu4VB/JxyEwSw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
