APP_URL: ENC[AES256_GCM,data:JHyb306GQ9EM6ABP1Erh,iv:TFGeo+Bkx8llBsLE4fQNvFwa2/BueqU6Ibq1cPXLjFA=,tag:KI3ag5w2AdWstnR69Egufw==,type:str]
CODE_REPO: ENC[AES256_GCM,data:kuZCJhHWjAoFmd4TekQ=,iv:hoDSAYPHiW0TxLrdos0Ddk7ML2ekrqwA49a+uJus7XQ=,tag:JSDX02ey3MwQHxmqYTPa/Q==,type:str]
PROJECT_DIR: ENC[AES256_GCM,data:IPOznPPqHsQE60WxKyV+s3bPbsTvC6Q4Jnj+kg==,iv:fH6dRIRdNFJZVpM92Vpe4XlRFXuLlGfvzaLCryHo7QM=,tag:1qvHxKG8LM8S49tCwBXBYQ==,type:str]
WEB_PORT: ENC[AES256_GCM,data:EVrePg==,iv:NQX4hGQFpGjLnDGznU+ZXBi71T0+QkxiRo3Kiuf9hOo=,tag:W8AMGwmrSY06woK3lO4Y2Q==,type:str]
APP_PORT: ENC[AES256_GCM,data:HIhJRGP5PETWi9qeBl4=,iv:BgSk4u8xMRSeCDRJvVUSa+DNdg4Nk2hdduPGn23mukA=,tag:24Lr1oncyMM81ul669Di2w==,type:str]
WEB_SERVER_USER: ENC[AES256_GCM,data:QqY8zAE/KAM=,iv:XguKkULfWO2uQ4ftbqscpxf6pkOwP/wYHc3JJ0FY8K8=,tag:bG/ewkZ13Dw7AivCtq2GKg==,type:str]
DOCKER_USERNAME: null
DOCKER_PASSWORD: null
DOCKER_EMAIL: ENC[AES256_GCM,data:H+0IF1zIUXcduy6zqSdfyV0/hw==,iv:gsK+WgQtSHmA/7ET/0OxkcmN0D+8A0NvFniwOGqnnCg=,tag:4Q7QF69hn4nth0Z/ww1roQ==,type:str]
DOCKER_REPO: ENC[AES256_GCM,data:agApMMsWRiTylUo4bjAIrES/RQ==,iv:/71aph/0M4U3jTajd1sqGvzMGPe1tt6P11cyK8/CwLc=,tag:oi0B38vW97jzWW9dC53dAg==,type:str]
DOCKER_PORTS:
    - ENC[AES256_GCM,data:SZcJ9zmI7bxGYxwnCDEFwSRi8w9oS5EYsdMCIuN4Ivea48wrcMSU,iv:AF6B1kZwIiyZGi3Cww4LQOPFvgZ5L00LJeadr76xLZ4=,tag:kUsWHFC36KJxcROcFOwH1Q==,type:str]
DOCKER_ENV:
    NEXT_PUBLIC_EXCHANGE_RATE_API_URL: ENC[AES256_GCM,data:D6F18BI0IJfptGOaIdfaH+FYCLRuo71TyXBQ28Nip991QZQ=,iv:oiWdUA8OTohogO8Jsy2calJXHJR1SJBiednpBDyb3g8=,tag:dlGrzsCWtvizl0jknlsEkA==,type:str]
    NEXT_PUBLIC_TRANSLATION_API_URL: ENC[AES256_GCM,data:inUJ/4YceB/gn4xhRMoPXhS63k4fQb0klsgFhgk65hm8f1s=,iv:N9iwixfyN3m+6kSPRf1nrEOzHwHq1xGMwmMb/mWMIbQ=,tag:IwPaiPkmMeDRWmMod9r0IA==,type:str]
    NEXT_PUBLIC_IMAGE_PROCESSING_API_URL: ENC[AES256_GCM,data:Io3lkwib+sp6UGRhXZY1Jq6LOdLQp6TgixUSuQE=,iv:0PjOHZ87kcg0v4eCuweay3ZR3a6PvPLHKgamsx7eQ7g=,tag:ZDOj6Bv1j0KmMkoXU7hZRw==,type:str]
    NEXT_PUBLIC_BARCODE_API_URL: ENC[AES256_GCM,data:V9WEzPADPbUc3h0Vt+qDzIytmAJNFhn34qOor+3bMQ==,iv:GKc84TClVbenKntAp8v8yJAzcGHh/yAB4HgV0fHuD+4=,tag:LoVy0zTN+bKlYxGmFZGM2Q==,type:str]
    NEXT_PUBLIC_PDF_API_URL: ENC[AES256_GCM,data:xpVYtmrrEpalbPeul34bliWgeF20SkqtP2IB,iv:MK/PPi4eEeJa7iW3MS1dHUCH/Myos5uMm0qwpu1Mjxk=,tag:5ZbSA3DlFZZFwGfSYYe2/w==,type:str]
    NEXT_PUBLIC_TAG_MANAGER_KEY: ENC[AES256_GCM,data:eF6DGt5et2uDS/jl,iv:5A57IbxZ7hqNW8rx3C0APqfD4Mhbuq3BqES7UQ5eg1A=,tag:2xNF2EGEx8zF2skNNvetWg==,type:str]
    NEXT_PUBLIC_SENTRY_AUTH_TOKEN: ENC[AES256_GCM,data:6r5ruKKKKv67O6lR2KyryAAFl3C/OGMOvR5Gp6Kf/TNeqgiZYgmMzAlLIg9S/iK6V0i9TFgB5rNKCyuQKpzy/5wH1sUieubeuFLifKRibBD/YxJzLicY4erm9NQ5EDuOkh5J9ClyWX/A7qUxuLeSLYGj1qYuf89o308BV3PDp5F6VZtO2RLf96Dlel6ASogX29mh5f1SUsJvJ6bzT3LqIw/ZP3tw5jXHOIrQR3yDHvGXCXJFRVBOzTQ9ANjsjwI=,iv:vYUL4rJKmzlLL6W4XHjlcVlGwKWwnPq52D3LP4OoGxo=,tag:bOJpYMcWwmicGJSwirQiGA==,type:str]
force_config: ENC[AES256_GCM,data:dMB/CA==,iv:yVqf+mdxTh+e2FfeKw/urcN9Pj+Csz/o7/tl+theuR8=,tag:F2apF/mZrgqEgLFirST4dQ==,type:bool]
LETSENCRYPT_EMAIL: ENC[AES256_GCM,data:xOcGPKx2sHOSOLpiOKsXLHdRAN54xQ==,iv:aaBSjORw8XWRGPyBVoYEjYLV3HuTihx7eaJZd+1L7DQ=,tag:sTAgdLQp+3OUBVxm7SAArw==,type:str]
LETSENCRYPT_DIR: ENC[AES256_GCM,data:QPbBUtaBGMeI3QPG5NqZMTZ6k8Hb,iv:c8dp/28XtCW0FP8sHyyUSl7z+wJ31PE93Cvsi1o0qXI=,tag:6s5WZEnB+NrbARiU5kYTBQ==,type:str]
certbot_create_if_missing: ENC[AES256_GCM,data:onpFCw==,iv:ArTC6QtZMtTE3BljHw1KmA/ZNNIiA2KcH61cWVlonro=,tag:lEQ8zdgcAo9I2idc7Vysyw==,type:bool]
certbot_dir: ENC[AES256_GCM,data:ghiaFmAooDeQGfAw8lLDDJg0itLv,iv:PsDRdwN9PPyA3Lk9KjJ4pz/5x3pgj8k8oIRQberP5mY=,tag:bOOU2kETK3GVMcaHCorx6g==,type:str]
certbot_create_standalone_stop_services:
    - ENC[AES256_GCM,data:ctxftWA=,iv:ZS68aQDTpMnL+rl/x9DEBcF9Ddw8cH3MNIRa9J6h/m8=,tag:MvHXd9ZidLNL+TNI9SfX3w==,type:str]
certbot_certs:
    - email: ENC[AES256_GCM,data:JU09JhYOqS+qQB2vsjZ7Nc44QRbaGdw=,iv:aXOg94wC3DB2csCCNqSgrnn0zOvVC1I+g1F6vqjJgQM=,tag:VBzn6sVTpmNjU1KWDFn+fg==,type:str]
      domains: ENC[AES256_GCM,data:QhoxXpkPnqQqns9M7Q==,iv:flUY0RSApNoMxUgkgyou0UpDt5S8rGa837p0xxd2wug=,tag:gE0seIcFGWyk8+l5+QnEVA==,type:str]
certbot_keep_updated: ENC[AES256_GCM,data:L7Jk,iv:8n0XPI3RqvCk3gb+j+v25XpkJM25sA71yMSo9IXlbqU=,tag:bbZztHpqB0Qf3aIQhbpxKQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:ap-southeast-1:143188609111:key/8fc6f01a-3289-4fb4-b9e7-cab31c54a4ea
          created_at: "2025-03-08T08:07:36Z"
          enc: AQICAHgxToX4Pp90hvfJQ4E9+h6aXlRo2IWXaPLiRXBaMnIbJwF2WpR03xl/qnNtFjQZHaDqAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMctvoThPqnPRViJBQAgEQgDvxhZBMOP3vj+OrayGcvsjAqK5ROWj1j6Vr3FYmwRSrxS7kphQ1o689JdX5evexLLMgNs7XK0LrlgIQPw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-08T08:07:36Z"
    mac: ENC[AES256_GCM,data:/tosBsSzKr/E9Id4pF/zettoBo/k0rMY4yhdDWvtSaGL8hkcK+g7ZJI+LDa1+SvcX7Vl/A2pCDVU/bjqqI9om7M5iqUODeCRCCZ6wqZ+s7moJWuY4/Ml7Qw5KhT3XVWoiIEShs/ymwgrSTZyB7NviL6uWT9R/dFvzooSdk8moUM=,iv:0wm2OKUVt4kT9zh8k00BmdMO0zROP+t/gzx3L92lyns=,tag:N3gB/GXhVFlKO1W0YprVmg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
