APP_URL: ENC[AES256_GCM,data:626sMxfTHrX/L6HXZjsrUxNNvsnCvg==,iv:0QVF5HfORJUH6MuPyJ+ESt0Et4kAq/bb6DmUTd688xE=,tag:tG+RxzgNC6dbk70BCn/ccA==,type:str]
CODE_REPO: ENC[AES256_GCM,data:YfE4VbqUFpLQzfTq0u8=,iv:6O2V39LmDh2+7FBhh/LhksXDP6hA6o7XCHtKpxGB+LE=,tag:ey1H4rPsyGs2sWhl2QlzDg==,type:str]
PROJECT_DIR: ENC[AES256_GCM,data:n3G5eV50UmAuCUddkR/nx4apRqi5FH1mF6DsyA==,iv:bOviZ+RV2l66kck488+9/x/+X4o5hBgf5QLXEWwdi3U=,tag:J2sj/g5M2UTPoifutjmPqQ==,type:str]
WEB_PORT: ENC[AES256_GCM,data:FfwCdw==,iv:r0W0NrMB7Mx0gO1R6e5moFn+aEL+SMmT/q2h/azbUmA=,tag:rF/ePrFSWkb6NtO2i9RsRg==,type:str]
APP_PORT: ENC[AES256_GCM,data:vewBrFlLV9iDWxnhr5Y=,iv:kz63m+RbtwArOxe6zyAQhjw8oZPwPVCemAGYa4iF5aw=,tag:7lX4T41oBljWQHrp/Rfdug==,type:str]
WEB_SERVER_USER: ENC[AES256_GCM,data:MSLYQMxCOis=,iv:W0N691YAO3qM1vw4C1y33gG8+mrp4FuDbpkM3LDwgNo=,tag:LOc+Z6kATan/xaJg5dR5hA==,type:str]
DOCKER_USERNAME: null
DOCKER_PASSWORD: null
DOCKER_EMAIL: ENC[AES256_GCM,data:4GvCDUFjofGBqMJqqaChq4EXrQ==,iv:Yrd4IARu3NWAZmNv/oQ7yjDN3NV+AZs0Mrlpb1AEDUw=,tag:k0WNOPUCgEY7Vd71WAOLdQ==,type:str]
DOCKER_REPO: ENC[AES256_GCM,data:gf6uiGMwQmffZ1W1vLxsMaaDTQ==,iv:QX+y+R2Q+iNGj3JCnrfXdHzvPnF9SdrswBReYNzH94k=,tag:0satds/ik1JMLi3h6/ukVg==,type:str]
DOCKER_PORTS:
    - ENC[AES256_GCM,data:n2ymbUb/W8CqKf10bUEt3cVhDo5BHgX1F7bEBVImb76k47JLpuZS,iv:FDBIlLL1G2HEzCZ8qlygELwlYr56Y10L5B9GiaJYX+A=,tag:1A+5XlFWsmDeLPKf5wHIfA==,type:str]
DOCKER_ENV:
    NEXT_PUBLIC_EXCHANGE_RATE_API_URL: ENC[AES256_GCM,data:+9e8dkaSBNNwa1yqVcucECdjcp5638A5qdZYR7bJroMQNv8=,iv:3g8pdR/dGc/TGBZ/jl3Ovw/XuzEpCcp+pno7PGwZ1os=,tag:sEyfTaF0tCoWpLPesO3ISQ==,type:str]
    NEXT_PUBLIC_TRANSLATION_API_URL: ENC[AES256_GCM,data:UWqCrfK+5lgSze6ZdCWxMmxqspsdWek0zb0mlhZ/UaQOJSU=,iv:psk4W/IEUyggfi6lFfJXVJvtDFvDA0863XMLSXWE020=,tag:aAf3KqbFQxsycNZ8o/nyVQ==,type:str]
    NEXT_PUBLIC_IMAGE_PROCESSING_API_URL: ENC[AES256_GCM,data:USGhhH+QkXUdqJWlRSCcIDx4YigHmCWugbYH5mM=,iv:2IfV8qXuPt8DfDZqasCrEkUvYYlTDdTUWMpYPherj7E=,tag:w1x+AvPNGnconN6c6dUzrw==,type:str]
    NEXT_PUBLIC_BARCODE_API_URL: ENC[AES256_GCM,data:YICzyKLK3Wge73GXLJ0HrnN8CnR9yGa3Kej1etwLsQ==,iv:sHpgn2X9JgRSWlEl+uwuodXY5JuAqBeCPoRbO18U4Ic=,tag:R3kKubLJdRkfALl3+u4mHQ==,type:str]
    NEXT_PUBLIC_PDF_API_URL: ENC[AES256_GCM,data:4KcegpxXdiXyk5DQZLqTdC9z9qmdZKNgjSas,iv:d43TxLWg2z9rZPK+mymGEYRpYaw1sJWkfEoK9eSGznI=,tag:S0iiOJRgzj6V8X6jrs/3oA==,type:str]
force_config: ENC[AES256_GCM,data:aun6Dw==,iv:EmZVBmUxr05scnYSmzocFCH7heJj1kKvOr6KBnhtBIQ=,tag:OSvSptqr0SuCOBElOdYdyw==,type:bool]
LETSENCRYPT_EMAIL: ENC[AES256_GCM,data:goxSYhMRNc+0c0Jhl04iIVPzfFNxk0bS,iv:8wvyZnk95dB1B2injqip6LbGbM7rgdkTwLWIxURZSUc=,tag:regCskyBVABDfdFCQ2ikgg==,type:str]
LETSENCRYPT_DIR: ENC[AES256_GCM,data:XVw8ETU0a+IOA66hu9S46CguxUmu,iv:WFO18vgfPtk3x29HPbqbAGcXMmI28SRqDKu187338Qo=,tag:NT0A1C6s36vDM1WI6eu70A==,type:str]
DOCKER_LOG_DRIVER: ENC[AES256_GCM,data:3z/tEDPiQA==,iv:rt0ichtZMBHWiiZhby5pobk4R/qdmQcR2scNFX7jHqA=,tag:E4aaU3Lo7rVhfq26QF5GHQ==,type:str]
DOCKER_LOG_OPTIONS:
    awslogs-region: ENC[AES256_GCM,data:EXMoLFKMMpk/oSuMeR4=,iv:NcCrbuEPQF5vWyozO/KcyEddp39zuBW7XrIlrEZy7Ow=,tag:XCk3UTsSO1NrbDL4wXESWw==,type:str]
    awslogs-group: ENC[AES256_GCM,data:V4GSavDTo+ZlTcfBNqpx9GbywNdN8P+0UXCi,iv:5BMoxKPkJAUPOWzHfkPzauS7D0xh0G/TtEo2XdPjwlE=,tag:kgupcly94hQ6lxWl9TkaGg==,type:str]
    awslogs-create-group: ENC[AES256_GCM,data:RkGd0g==,iv:BdPfyV8faNrP/SDaNvPasDJyPsSKLQ2lCxJ2URNXDI0=,tag:/e08Ow1sOCwidbg+HAUQlQ==,type:bool]
    awslogs-stream: ENC[AES256_GCM,data:XAupI5e9b9g+lsaqteDCoxdf4a+GcBg=,iv:J3RZtZrNBIKiRV4hyMPBOOXpNAwX9OsBtD9bvD7gziI=,tag:eR+wvKEYrAccCI5MPkUQ3w==,type:str]
certbot_create_if_missing: ENC[AES256_GCM,data:sW9Yew==,iv:2CK0MJziVZ40WvacTUFA5tj80NOz+bf5KzUCDZCqduQ=,tag:ps1y7RUzvITHwVLnIcTj6w==,type:bool]
certbot_dir: ENC[AES256_GCM,data:o7I+OnqZW0Pr2SB0Pde+qA2jRp3s,iv:6+wdvt0lntJNvWCZQI6VmFaffUobI9k2BVR+dJcawdo=,tag:IsgjFmE7Ex1OYiiGW2Ad0Q==,type:str]
certbot_create_standalone_stop_services:
    - ENC[AES256_GCM,data:44mlgnA=,iv:qUulR3WYz7OngYKRsZ6eBx5V1JTGjB+ct4YWoie82hE=,tag:SczX6zeF3oGwnrSxm2Pz2w==,type:str]
certbot_certs:
    - email: ENC[AES256_GCM,data:xf6AJ2NassUJUjHnzMPneqG2YcA79E8=,iv:HkWHHz3zAkT1AxkAhi5vCKHJ1yfv8wB7SyiNhv51e8Q=,tag:skUlffSAVSJTfW1h4Wagkg==,type:str]
      domains: ENC[AES256_GCM,data:m376rRoQYrMSngBFHC2dgWHjU7Nk3APxa+xOPM0dSQc=,iv:mggR8WLubuEAHXwaid6XRwUUzVlloZQs74TZeOhxb0U=,tag:8QQxPEAMw+VkGfY0ohZ8fg==,type:str]
certbot_keep_updated: ENC[AES256_GCM,data:9LO6,iv:IyeMSw8CtKO2rw+cznUFey1kSJxdIBYgzAll/FPtZQM=,tag:ykoUVGU+vgHlmbHux83UGg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:ap-southeast-1:143188609111:key/8fc6f01a-3289-4fb4-b9e7-cab31c54a4ea
          created_at: "2025-03-07T16:00:52Z"
          enc: AQICAHgxToX4Pp90hvfJQ4E9+h6aXlRo2IWXaPLiRXBaMnIbJwGUkKeiEnNjEOhNXFy6lOy/AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMobHlYOfIzINLjdz9AgEQgDsUYHbtgc7Bi7oiGsXhRTlM2meW4j5zVxx0BlAapBHuEscpgKYX2foVwmbGyBiTFQ8J0eDO0Brwo1LPaw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-07T16:00:52Z"
    mac: ENC[AES256_GCM,data:WPj42fVEs3CdsbIoWSDZuI9wxyx5ynyhPAt7jBzfGr63dshX+pSAzVpcMyh7j7Q9l05iYkUvMeybofnman1GDpxnHRCWchG58C5I9ytrXJr1YjTS0YGA30LYsfmAqZuX9VBEIq2zi2kTGdrTu/CcX1cIYJz9K4bw79ZwVr+ORvw=,iv:UeFCnOAovyzEwRXNyDtPocePky9mJjRQ+dxfHIkfM68=,tag:V+inI7WHskJn/e/xK6Od1Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
