name: Deployment to Tipsy server

on: 
  push:
    tags:
      - v**-rc*
      - V**-rc*
    branches:
      - dev
env:
  docker: monkeymon/web-tools
jobs:
  build:
    runs-on: ubuntu-latest
    environment: tipsy
    steps:
    - uses: actions/checkout@v3
    # - name: Use Node.js
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: 20
    # - name: npm install, build
    #   run: |
    #     npm install
    #     npm run build
    #   env: 
    #     NEXT_SHARP_PATH: node_modules/sharp
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
      id: extract_branch
    - name: Build and Push image
      uses: DailyVanity/Publish-Docker-Github-Action@master
      with:
        name: ${{ env.docker}}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Dockerfile
        tags: "dev-latest,${{ steps.extract_branch.outputs.branch }}"        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
        id: extract_branch
      - name: Execute Ansible Playbook - Tipsy
        uses: DailyVanity/ansible-playbook-docker-action@master
        with:
          playbookName: '.ansible/deployment.yml'
          inventoryFile: '.ansible/inventories/tipsy/hosts'
          requirementsFile: '.ansible/requirements-ci.yml'
          key: ${{ secrets.CI_PRIVATE_KEY }}
          keyFileVaultPass: ${{ secrets.ANSIBLE_VAULT_PASS }}
          extraVars: |
            -e DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }} 
            -e DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }} 
            -e DOCKER_REPO_TAG=${{ steps.extract_branch.outputs.branch }} 
            -e PROJECT_TAG=${{ steps.extract_branch.outputs.branch }}
            -e DOCKER_REPO=${{ env.docker}}
          galaxyGithubUser: ${{ secrets.GIT_USERNAME }}
          galaxyGithubToken: ${{ secrets.GIT_PASSWORD }}
          rolesPath: ".ansible/roles"

